eck-elasticsearch:
  enabled: true
  fullnameOverride: elasticsearch
  annotations:
    eck.k8s.elastic.co/license: basic

  spec:
    count: 1
    http:
      service:
        spec:
          type: LoadBalancer
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteMany
          persistentVolumeReclaimPolicy: Retain
          resources:
            requests:
              storage: 5Gi
          storageClassName: eck-elastic-storage  # Updated storage class name here

eck-kibana:
  enabled: true
  fullnameOverride: kibana
  annotations:
    eck.k8s.elastic.co/license: basic

  spec:
    count: 1
    elasticsearchRef:
      name: elasticsearch
    http:
      service:
        spec:
          type: LoadBalancer
    podTemplate:
      spec:
        containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2
          volumeMounts:
            - name: kibana-data
              mountPath: /usr/share/kibana/data
        volumes:
          - name: kibana-data
            persistentVolumeClaim:
              claimName: elasticsearch-data  # Using the same PVC claim name as in Elasticsearch
