eck-elasticsearch:
  enabled: true
  fullnameOverride: elasticsearch
  annotations:
    eck.k8s.elastic.co/license: basic

  spec:
    count: 1
    http:
      service:
        spec:
          type: LoadBalancer
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        storageClassName:  azureblob-nfs-premium # Use the StorageClass created earlier
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi  # Change the storage size as needed

eck-kibana:
  enabled: true
  fullnameOverride: kibana
  annotations:
    eck.k8s.elastic.co/license: basic

  spec:
    count: 1
    elasticsearchRef:
      name: elasticsearch
    http:
      service:
        spec:
          type: LoadBalancer
    podTemplate:
      spec:
        containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2
eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-beats:
  enabled: false
  annotations:
    eck.k8s.elastic.co/license: basic
