apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eck-elastic-storage
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  location: eastus2
  storageAccount: eckstorageaccount
  protocol: nfs
  allowBlobPublicAccess: false
  resourceGroup: ncs-neogrid-cloud-storage-dev
volumeBindingMode: Immediate
