apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elastic-storage-class
  namespace: elastic-stack
provisioner: blob.csi.azure.com
parameters:
  protocol: nfs
  tags: environment=Development
  skuName: Standard_LRS
  location: eastus2
  resourceGroup: ncs-neogrid-cloud-storage-dev
  containerName: elasticsearch-data
  storageAccount: elasticstoragelog
  storeAccountKey: true
  secretName: elastic-storage-account-secret
  secretNamespace: elastic-stack
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
