apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eck-elastic-storage
provisioner: blob.csi.azure.com
parameters:
  protocol: nfs
  tags: environment=Production
volumeBindingMode: Immediate
