apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elastic-storage-class
  namespace: elastic-stack
provisioner: blob.csi.azure.com
parameters:
  protocol: nfs
  tags: environment=Development
  skuName: Standard_LRS
  resourceGroup: ncs-neogrid-cloud-storage-dev
  secretName: elastic-storage-account-secret
  storageAccount: elasticstoragelog
  secretNamespace: elastic-stack
  storeAccountKey: true 
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain   # Retain or Delete
allowVolumeExpansion: true 
