apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elastic-storage-class
  namespace: elastic-stack
provisioner: blob.csi.azure.com
parameters:
  skuName: Standard_LRS  # Especifique o SKU da conta de armazenamento (Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS)
  resourceGroup: ncs-neogrid-cloud-storage-dev  # Especifique o nome do grupo de recursos do Azure
  storageAccount: elasticstoragelog  # Especifique o nome da conta de armazenamento do Azure
  containerName: elasticsearch-data  # Especifique o nome do contêiner de Blob existente
  protocol: nfs
  secretName: elastic-storage-account-secret  # Especifique o nome da secret que contém as credenciais
  secretNamespace: elastic-stack  # Especifique o namespace da secret (padrão é "default" se não especificado)
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: true
