---
eck-elasticsearch:
  enabled: true
  annotations:
      eck.k8s.elastic.co/license: basic
  fullnameOverride: elasticsearch 
  transport: 
    spec:
      type: LoadBalancer
  http: 
    spec:
      type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true

eck-kibana:
  enabled: true
  annotations:
      eck.k8s.elastic.co/license: basic
  spec:
    elasticsearchRef:
      name: elasticsearch


eck-agent:
  enabled: false


eck-fleet-server:
  enabled: false


eck-beats:
  enabled: false
