eck-elasticsearch:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  fullnameOverride: elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic-storage-class 
        persistentVolumeReclaimPolicy: Retain
        csi:
          driver: blob.csi.azure.com
          readOnly: false
          volumeHandle: elasticstoragelog # Substitua "unique-volumeid" por um identificador único para o volume
          volumeAttributes:
            resourceGroup: ncs-neogrid-cloud-storage-dev  # Especifique o nome do grupo de recursos do Azure
            storageAccount: elasticstoragelog  # Especifique o nome da conta de armazenamento do Azure
            containerName: elasticsearch-data  # Especifique o nome do contêiner de Blob existente
            protocol: nfs
            secretName: elastic-storage-account-secret  # Especifique o nome da secret que contém as credenciais
            secretNamespace: elastic-stack  # Especifique o namespace da secret (padrão é "default" se não especificado)

eck-kibana:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  spec:
    count: 1
    elasticsearchRef:
      name: elasticsearch
    http:
      service:
        spec:
          type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true
    podTemplate:
      spec:
        containers:
          - name: kibana
            env:
              - name: NODE_OPTIONS
                value: "--max-old-space-size=2048"
            resources:
              requests:
                memory: 1Gi
                cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2

eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-beats:
  enabled: false
