---
eck-elasticsearch:
  enabled: true
  annotations:
      eck.k8s.elastic.co/license: basic
  fullnameOverride: elasticsearch 
  transport: 
    spec:
      type: LoadBalancer
  http: 
    spec:
      type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true
nodeSets:
- name: masters
  count: 1
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

eck-kibana:
  enabled: true
  annotations:
      eck.k8s.elastic.co/license: basic
  spec:
    elasticsearchRef:
      name: elasticsearch


eck-agent:
  enabled: false


eck-fleet-server:
  enabled: false


eck-beats:
  enabled: false
