eck-elasticsearch:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  fullnameOverride: elasticsearch 
 
eck-kibana:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  spec:
    count: 1
    elasticsearchRef:
      name: elasticsearch
    http:
      service:
        spec:
          type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true
    podTemplate:
      spec:
        containers:
          - name: kibana
            env:
              - name: NODE_OPTIONS
                value: "--max-old-space-size=2048"
            resources:
              requests:
                memory: 1Gi
                cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2

eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-beats:
  enabled: false
