---
eck-elasticsearch:
  enabled: true
  annotations:
      eck.k8s.elastic.co/license: basic
  fullnameOverride: elasticsearch 
  count: 1
  nodeSets:
  - name: masters
    count: 3
    config:
      node.roles: ["master"]
      xpack.ml.enabled: true
      node.remote_cluster_client: false
  - name: data
    count: 1
    config:
      node.roles: ["data", "ingest", "ml", "transform"]
      node.remote_cluster_client: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

eck-kibana:
  enabled: true
  annotations:
      eck.k8s.elastic.co/license: basic
  spec:
    count: 1
    elasticsearchRef:
      name: elasticsearch
    http:
      service:
        spec:
          type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true
    podTemplate:
      spec:
        containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2
    

eck-agent:
  enabled: false


eck-fleet-server:
  enabled: false


eck-beats:
  enabled: false
