apiVersion: v1
kind: Secret
metadata:
  name: elastic-storage-account
  namespace: elastic-stack
type: Opaque
data:
  azurestorageaccountkey: "base64_encoded_secret"
  azurestorageaccountname: "base64_encoded_name"   
