eck-elasticsearch:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  fullnameOverride: elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: 1
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 4
          volumeMounts:
          - name: elasticsearch-data-master
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        namespace: elastic-stack
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: elastic-storage

  - name: hot
    count: 1
    config:
      node.roles: ["data_hot", "data_content", "ingest"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 4
          volumeMounts:
          - name: elasticsearch-data-hot
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        namespace: elastic-stack
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: elastic-storage

  - name: warm
    count: 1
    config:
      node.roles: ["data_warm"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 4
          volumeMounts:
          - name: elasticsearch-data-warm
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        namespace: elastic-stack
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: elastic-storage

  - name: cold
    count: 1
    config:
      node.roles: ["data_cold"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 4
          volumeMounts:
          - name: elasticsearch-data-cold
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        namespace: elastic-stack
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: elastic-storage

eck-kibana:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  spec:
    count: 1
    elasticsearchRef:
      name: elasticsearch
    http:
      service:
        spec:
          type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true
    podTemplate:
      spec:
        containers:
          - name: kibana
            env:
              - name: NODE_OPTIONS
                value: "--max-old-space-size=4096"
            resources:
              requests:
                memory: 4Gi
                cpu: 1
            limits:
              memory: 8Gi
              cpu: 2

eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-beats:
  enabled: false
